### ISSUE TITLE
keyczar: key not found - only on production

### ISSUE THREAD

**Issue by fmpwizard** [dgryski/dkeyczar#22]
Hi,

At work we use the java keyczar library to encrypt and decrypt data, we use the AES cypher. During development, we have a dummy meta and key and I was able to use this library to decrypt text that was encrypted with the java library (the web app is actually in Scala).

Then I moved the Go code to production, where we fetch the encryption key from a key server (so I had to write a separate `KeyReader` that knew how to fetch the meta and key values from our key server)

Now text that is encrypted on the web app using Scala/java is not decrypted by Go, I get the error key not found.

I was able to track it down to:

https://github.com/dgryski/dkeyczar/blob/05c8ea381e02781927d6c633076910b86c6ce770/keyczar.go#L1004

this line

`lookup.getKeyForID(b[1:5])`

which is then converted  with `binary.BigEndian.Uint32`

returns a value like 

`2829747566`
but the stored in memory keyID is
`2628606745`

Now, I have no idea why in dev mode locally I can decrypt data (and the `lookup.getKeyForID` gives the right value ) but it fails on the web app.

Any hints?

Thanks!

**Comment by fmpwizard** [comment]
The issue was that on production, we use one key to decrypt another key which is the one actually used to encrypt/decrypt our data in the database. So, I was using the wrong key for the wrong task.

**Comment by dgryski** [comment]
Glad you got this sorted out :)
